### PR TITLE
Added performance enhancements to reduce CPU Load of video streaming

### PR DESCRIPTION
**Pull request by acedrew**
Added delays to both client and server side of code to ensure that approximately 30fps is being captured. 
Because we're using mjpeg streams, the network cameras will happily dump their buffer every you ask them to, leading to over saturation of network resources.

Moved the jpeg generation so that it only happens once per frame, preventing repeated encoding of the same frame.

Added parameter for jpeg quality, lower quality typically requires additional processing, and obviously we don't want quality too low, most web things tend toward 70%, but that's generally given a much more sophisticated encoding process than what opencv is offering, this parameter may need to be tweaked to get optimal performance.

### CODE REVIEW

**Comment by acedrew** [comment]
I took this off the production code last night, using pyflame as so:

cd ~/Downloads/FlameGraph
sudo pyflame -s 5 -r 0.01 -p <pid of streaming server> --threads | ./flamegraph.pl > 2019-03-20-19273.svg

image

I'd love to see what effect the changes in the PR above have on this, from my testing locally, it looks like it should be fairly significant.

**Review by oitsjustjose — APPROVED** [review]
👍 Looks good! I need to run black on Login Manager too. Otherwise, this is a good change that I hadn't previously considered as a performance problem.

**Comment by acedrew** [comment]
@oitsjustjose what I was worried about was the interface to https://github.com/ut-cuip/utc-cuip-video-event-producer/blob/master/processors/frame_processor.py 

It looks like it won't introduce any issues to me, but you're much more familiar with that code than I am. I was only able to test this on its own on my laptop

**Comment by acedrew** [comment]
I realized the big difference in testing and production that was causing the delta in performance increase between the two. I was testing in a single process environment, increasing the throughput and reducing the load of a single process, but with multiprocessing the linux kernel is handling some of that.
I'm going to keep this open for a bit because I still think there are some optimizations we can get that move us to a GPU bound model

**Pull request merged**
